/**
 * CODE SNIPPETS for server.js
 * 
 * These show how to:
 * 1. Pass layoutArchetype through the generation pipeline
 * 2. Rotate through A→B→C→D for each post
 */

// ============================================================================
// SNIPPET 1: Update createScheduledPostForTomorrow()
// ============================================================================
// FIND: async function createScheduledPostForTomorrow({ workspace, account, brand, targetDate, targetTime, scheduledAt, scheduleSlotKey })
// REPLACE THE FUNCTION BODY WITH:

async function createScheduledPostForTomorrow({ workspace, account, brand, targetDate, targetTime, scheduledAt, scheduleSlotKey }) {
  const timeZone = brand.timezone || workspace.settings?.defaultTimezone || schedulerTimezone;
  const targetDay = getZonedParts(new Date(scheduledAt), timeZone);
  const strategyItem = (brand.weeklyStrategy || []).find(s => s.day === targetDay.weekdayName);

  // NEW: Calculate layout archetype for this post (rotate A→B→C→D)
  const accountPostCount = workspace.posts.filter(p => p.accountId === account.id).length;
  const archetypeLetters = ['A', 'B', 'C', 'D'];
  const layoutArchetype = archetypeLetters[accountPostCount % 4];

  const prompt = buildGenerationPrompt({ 
    account, 
    brand, 
    targetDate, 
    targetTime, 
    strategyItem,
    layoutArchetype  // PASS THIS
  });
  
  const { content, title } = await generatePostContent({ account, brand, prompt });
  const theme = strategyItem?.topic || brand.contentThemes?.[Math.abs(scheduleSlotKey.length) % Math.max(brand.contentThemes.length, 1)] || brand.contentPillars?.[0] || 'general';

  const kicker = theme.charAt(0).toUpperCase() + theme.slice(1);
  const graphicHtml = await generateGraphicHtml({
    account,
    brand: {
      ...brand,
      visualDirection: strategyItem?.visualDirection,
      visualState: strategyItem?.visualState
    },
    title,
    content,
    kicker,
    logoUrl: brand.logoUrl || workspace.settings.logoUrl,
    layoutArchetype  // PASS THIS
  });
  
  return {
    id: `post_${Date.now()}_${account.id}`,
    accountId: account.id,
    title,
    theme,
    content,
    cta: brand.ctaStyle || '',
    hashtags: brand.hashtags || [],
    htmlAsset: graphicHtml,
    status: 'scheduled',
    scheduledAt: scheduledAt.toISOString(),
    generatedAt: new Date().toISOString(),
    scheduleSlotKey,
    generationSource: 'daily_5am_scheduler',
    metrics: { impressions: 0, reactions: 0, comments: 0, clicks: 0, shares: 0 },
    notes: 'Generated by the daily 5 AM scheduler.',
    retryCount: 0,
  };
}


// ============================================================================
// SNIPPET 2: Update buildGenerationPrompt() signature and first line
// ============================================================================
// FIND: function buildGenerationPrompt({ account, brand, title, content, kicker, logoUrl, visualDirection, visualState })
// REPLACE WITH:

function buildGenerationPrompt({ account, brand, targetDate, targetTime, strategyItem, layoutArchetype = 'A' }) {
  let dayOfWeek = '';
  try {
    dayOfWeek = new Date(targetDate).toLocaleDateString('en-US', { weekday: 'long' });
  } catch { dayOfWeek = targetDate; }
  const pillarsStr = (brand.contentPillars || []).join(', ');
  const themesStr = (brand.contentThemes || []).join(', ');

  return `Write one LinkedIn post for ${account.name}, scheduled for ${dayOfWeek} at ${targetTime}.

Design Note: This post will be rendered using Layout Archetype ${layoutArchetype} from the brand design system. Each post in the week will use a different archetype (A, B, C, D) to ensure variety and freshness.

${strategyItem ? `## AI Strategy Direction
Topic: ${strategyItem.topic}
Hook Idea: ${strategyItem.hook}
Strategic Angle: ${strategyItem.angle}

Implement this specific idea creatively.` : `## Content Pillars
Pick ONE for this post, vary across the week: ${pillarsStr}`}

## Account context
- Type: ${account.type === 'organization' ? 'Company page' : 'Personal founder/executive profile'}
- About: ${trimContext(brand.aboutCompany || '', 1000)}
- Brand voice: ${trimContext(brand.voice || '', 1000)}
- Tone: ${brand.tone}
- Writing style: ${brand.writingStyle}
- Content themes: ${themesStr}
- CTA style: ${brand.ctaStyle}
- Preferred hashtags: ${(brand.hashtags || []).join(' ')}
- Banned topics: ${(brand.bannedTopics || []).join(', ')}

## LinkedIn post philosophy
The brand voice page is the primary source of truth. Follow the account context, brand voice, writing style, CTA style, content themes, and banned topics above. The company is based in India and writes for an India-based audience, but do not force India-specific legal frameworks, terminology, or currency unless the topic or brand profile calls for it. The best LinkedIn posts feel like a smart practitioner sharing a genuine observation with a colleague, not like a marketer running a campaign.

## Required post structure
1. **Hook (line 1 only)** — A single punchy line that makes a specific claim, shares a surprising observation, or opens a story moment. Good hooks are concrete and specific. Bad hooks: "I'm excited to share", "Here are X tips", "Let's talk about", "The truth about". Make it interesting enough that someone would stop scrolling.

2. **Body (2-4 short paragraphs, blank line between each)** — Build on the hook with a story, observation, or practical insight. Ground it in real experience or a specific situation. Include a "why this matters" angle. Each paragraph is 1-3 short sentences. NO bullet lists unless the post is genuinely a framework/checklist (max 4 items even then).

3. **Close (1 line)** — A specific, open-ended question that invites a real conversation. NOT "Save this!", "Like if you agree!", "Drop a comment", or "What do you think?" — it must relate directly to the topic and be specific enough that it has a real answer.

4. **Hashtags** — 3 to 5 relevant hashtags on the final line.

## Hard rules
- Word count: 120-280 words total
- Do NOT use: "I'm thrilled/excited/proud to share/announce", "Game changer", "Disruptive", "Synergy", "Leverage" (as a verb), "Holistic", "Empower", "Transform your X", "Here's the thing", "Let's be real", "At the end of the day"
- Do NOT use fake urgency, engagement bait, or manipulation
- Do NOT use bullet lists for the main content
- Do NOT use **markdown bold**, _italic_, # headers
- Do NOT wrap the post in quotes
- Return only the post text — no title, no label, no preamble

## Format
Plain text. Blank lines between paragraphs. Hashtags on the last line only.`;
}


// ============================================================================
// SNIPPET 3: Update buildBatchGenerationPrompt() for weekly batch
// ============================================================================
// FIND: function buildBatchGenerationPrompt({ account, brand, slots = [] })
// REPLACE THE FIRST LINE AND ADD layoutArchetype:

function buildBatchGenerationPrompt({ account, brand, strategyItem, layoutArchetype = 'A' }) {
  // ... existing code ...
  
  return `You are a world-class LinkedIn content writer. Write one high-performance post for ${account.name}.

Design Context: This post will use Layout Archetype ${layoutArchetype} from the brand design system. Your written content should be compelling enough to work with that layout structure.

${strategyItem ? `## AI Strategy Direction
Topic: ${strategyItem.topic}
Hook Idea: ${strategyItem.hook}
Angle: ${strategyItem.angle}

Implement this specific idea creatively.` : `## Content Pillars
Pick ONE, vary across the week: ${(brand.contentPillars || []).join(', ')}`}

... [rest of existing prompt]

## OUTPUT FORMAT
You MUST return the post in valid JSON format only. Do not include any text outside the JSON.
JSON Structure:
{
  "title": "A short, punchy 3-5 word internal title for this post",
  "content": "The full LinkedIn post text, including the hook, body, close, and hashtags exactly as requested above."
}`;
}


// ============================================================================
// SNIPPET 4: Update the weekly batch polling to pass layoutArchetype
// ============================================================================
// FIND: const graphicsRequests = [];
// ADD THIS BEFORE THE LOOP:

const graphicsRequests = [];
const archetypeLetters = ['A', 'B', 'C', 'D'];

// THEN INSIDE THE LOOP, when building graphicPrompt:
const idx = parseInt(res.custom_id.split('_').pop());
const strategyItem = brand.weeklyStrategy?.[idx];
const layoutArchetype = archetypeLetters[idx % 4];

const graphicPrompt = buildGraphicPrompt({
  account,
  brand,
  title: generated.title,
  content: generated.content,
  kicker: strategyItem.topic,
  logoUrl: brand.logoUrl || workspace.settings.logoUrl,
  visualState: strategyItem?.visualState,
  visualDirection: strategyItem?.visualDirection,
  layoutArchetype  // ADD THIS
});

// ============================================================================
// SNIPPET 5: Update the graphics batch result processing
// ============================================================================
// FIND: else if (brand.batchStatus === 'processing_graphics') {
// IN THE LOOP WHERE YOU CREATE POSTS:

for (const res of results) {
  if (res.result.type !== 'succeeded') continue;

  const idx = parseInt(res.custom_id.split('_').pop());
  const strategyItem = brand.weeklyStrategy?.[idx];
  if (!strategyItem || !strategyItem.generatedContent) continue;
  
  const timeZone = strategyItem.timezone || brand.timezone || workspace.settings?.defaultTimezone || schedulerTimezone;
  if (hasExistingPostForSlot(
    workspace,
    brand.accountId,
    strategyItem.targetDate,
    strategyItem.scheduleSlotKey,
    timeZone,
  )) {
    continue;
  }

  let html = normalizeGraphicHtml(res.result.message.content[0].text);
  if (!(html.includes('<html') || html.includes('<!doctype html')) || !hasVisiblePosterText(html)) {
    const account = workspace.accounts.find(a => a.id === brand.accountId);
    const accountHandle = account?.linkedInUrl
      ? account.linkedInUrl.replace(/\/$/, '').split('/').pop() || account.name
      : account?.name || '';
    html = createHtmlAsset(
      strategyItem.generatedContent.title,
      strategyItem.generatedContent.content,
      brand.imageStyle || strategyItem.topic || 'Featured',
      brand.logoUrl || workspace.settings.logoUrl,
      account?.type !== 'person',
      account?.name || '',
      accountHandle,
    );
  }

  const post = {
    // ... existing post fields ...
  };
  workspace.posts = [post, ...(workspace.posts || [])];
  createdCount += 1;
}


// ============================================================================
// SNIPPET 6: Update generatePostRemote endpoint to include layoutArchetype
// ============================================================================
// FIND: app.post(['/api/generate-post', '/linkedin/api/generate-post'], async (req, res) => {
// ADD THIS LOGIC:

app.post(['/api/generate-post', '/linkedin/api/generate-post'], async (req, res) => {
  const { accountId, prompt } = req.body;
  const workspace = await loadWorkspace();
  const account = workspace.accounts.find(a => a.id === accountId);
  const brand = workspace.brandProfiles.find(b => b.accountId === accountId);

  if (!account || !brand) {
    res.status(400).json({ error: 'Account or brand profile not found' });
    return;
  }

  // NEW: Calculate layout archetype for this post
  const accountPostCount = workspace.posts.filter(p => p.accountId === accountId).length;
  const archetypeLetters = ['A', 'B', 'C', 'D'];
  const layoutArchetype = archetypeLetters[accountPostCount % 4];

  const generated = await generatePostContent({
    account,
    brand,
    prompt: prompt || buildGenerationPrompt({
      account,
      brand,
      targetDate: getZonedParts(new Date(), brand.timezone || schedulerTimezone).dateKey,
      targetTime: getZonedParts(new Date(), brand.timezone || schedulerTimezone).timeKey,
      strategyItem: null,
      layoutArchetype  // PASS THIS
    }),
  });

  const postTheme = brand.contentThemes?.[0] || brand.contentPillars?.[0] || 'general';
  const kicker = postTheme.charAt(0).toUpperCase() + postTheme.slice(1);
  const post = {
    // ... existing fields ...
    htmlAsset: await generateGraphicHtml({
      account,
      brand,
      title: generated.title,
      content: generated.content,
      kicker,
      logoUrl: brand.logoUrl || workspace.settings.logoUrl,
      layoutArchetype  // PASS THIS
    }),
    // ... rest of post object ...
  };

  res.json(post);
});
